package GPP_Testing

import gppBuilder.GPPbuilder

def build = new GPPbuilder()
String rootPath = "./"  // as required for use in Intellij

build.runBuilder(rootPath + "Test1")
build.runBuilder(rootPath + "Test1Vis")
build.runBuilder(rootPath + "Test2")
build.runBuilder(rootPath + "Test2Vis")
build.runBuilder(rootPath + "Test3")
build.runBuilder(rootPath + "Test3Vis")
build.runBuilder(rootPath + "Test4")
build.runBuilder(rootPath + "Test4Vis")
build.runBuilder(rootPath + "Test5")
build.runBuilder(rootPath + "Test5Vis")
build.runBuilder(rootPath + "Test6")
build.runBuilder(rootPath + "Test6Vis")
build.runBuilder(rootPath + "Test7")
build.runBuilder(rootPath + "Test7Vis")
build.runBuilder(rootPath + "Test8")
build.runBuilder(rootPath + "Test8Vis")
build.runBuilder(rootPath + "Test9")
build.runBuilder(rootPath + "Test9Vis")
build.runBuilder(rootPath + "Test10")
build.runBuilder(rootPath + "Test10Vis")
build.runBuilder(rootPath + "Test11")
build.runBuilder(rootPath + "Test11Vis")
build.runBuilder(rootPath + "Test12")
build.runBuilder(rootPath + "Test12Vis")
build.runBuilder(rootPath + "Test13")
build.runBuilder(rootPath + "Test13Vis")
build.runBuilder(rootPath + "Test14")
build.runBuilder(rootPath + "Test14Vis")
build.runBuilder(rootPath + "Test15")
build.runBuilder(rootPath + "Test15Vis")
build.runBuilder(rootPath + "Test16")
build.runBuilder(rootPath + "Test16Vis")
build.runBuilder(rootPath + "Test17")
build.runBuilder(rootPath + "Test17Vis")
build.runBuilder(rootPath + "Test18")
build.runBuilder(rootPath + "Test18Vis")
build.runBuilder(rootPath + "Test19")
build.runBuilder(rootPath + "Test19Vis")
build.runBuilder(rootPath + "Test20")
build.runBuilder(rootPath + "Test20Vis")
build.runBuilder(rootPath + "Test21")
build.runBuilder(rootPath + "Test21Vis")
build.runBuilder(rootPath + "Test22")
build.runBuilder(rootPath + "Test22Vis")
build.runBuilder(rootPath + "Test23")
build.runBuilder(rootPath + "Test23Vis")
build.runBuilder(rootPath + "Test24")
build.runBuilder(rootPath + "Test24Vis")
build.runBuilder(rootPath + "Test25")
build.runBuilder(rootPath + "Test25Vis")
build.runBuilder(rootPath + "Test26")
build.runBuilder(rootPath + "Test26Vis")
build.runBuilder(rootPath + "Test27")
build.runBuilder(rootPath + "Test27Vis")
build.runBuilder(rootPath + "Test28")
build.runBuilder(rootPath + "Test28Vis")
build.runBuilder(rootPath + "Test29")
build.runBuilder(rootPath + "Test29Vis")
build.runBuilder(rootPath + "Test30")
build.runBuilder(rootPath + "Test30Vis")
build.runBuilder(rootPath + "Test31")
build.runBuilder(rootPath + "Test31Vis")
build.runBuilder(rootPath + "Test32")
build.runBuilder(rootPath + "Test32Vis")
build.runBuilder(rootPath + "Test33")
build.runBuilder(rootPath + "Test33Vis")
build.runBuilder(rootPath + "Test34")
build.runBuilder(rootPath + "Test34Vis")
build.runBuilder(rootPath + "Test34a")
build.runBuilder(rootPath + "Test34aVis")
build.runBuilder(rootPath + "Test35")
build.runBuilder(rootPath + "Test35Vis")
build.runBuilder(rootPath + "Test36")
build.runBuilder(rootPath + "Test36Vis")
// these use cluster connectors and cannot be tested using builder
//build.runBuilder(rootPath + "Test37")
//build.runBuilder(rootPath + "Test38")
//build.runBuilder(rootPath + "Test39")
//build.runBuilder(rootPath + "Test40")
//end of cluster connector tests
build.runBuilder(rootPath + "Test41")
build.runBuilder(rootPath + "Test41Vis")
build.runBuilder(rootPath + "Test42")
build.runBuilder(rootPath + "Test42Vis")
build.runBuilder(rootPath + "Test43")
build.runBuilder(rootPath + "Test44")
build.runBuilder(rootPath + "Test45")
build.runBuilder(rootPath + "Test46")
build.runBuilder(rootPath + "Test47")
build.runBuilder(rootPath + "Test48")
build.runBuilder(rootPath + "Test49")
